source("Functions/CodonTable.R")
source("Functions/TryCatch2.R")
source("Functions/GenerateMutatedSeq.R")
source("Functions/GenerateIndelSeq.R")
source("Functions/GenerateListForGetRNASeq.R")
source("Functions/GetRNAseq.R")
source("Functions/GetRNAseq_indel.R")
source("Functions/TryCatch2.R")
source("Functions/GenerateListForCCFP.R")
source("Functions/GetRatio.R")
source("Functions/MainSNVClass1.R")
source("Functions/MainSNVClass2.R")
source("Functions/MainINDELClass1.R")
source("Functions/MainINDELClass2.R")
source("Functions/MainMergeSNVClass1.R")
source("Functions/MainMergeSNVClass2.R")

print("Read All Functions.")