---
title: "SampleCodeForNeoantimon"
author: "T. Hasegawa"
date: "2018/05/02"
output: html_document
---

<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Sample Code to Use Neoantimon}
-->

## Data Preparation and Sample Codes for Analysis
```{r Preparation}
#install.packages('devtools');
library(devtools);
install_github('hase62/Neoantimon');
library(Neoantimon);
```

```{r Sample VCF file}
data("sample_vcf")
head(sample_vcf, row.names = FALSE)
```

```{r Sample VCF (SV Fusion BND) file}
data("sample_sv_bnd")
head(sample_sv_bnd, row.names = FALSE)
```

```{r HLA Table for Class 1}
library(Neoantimon)
data("sample_hla_table_c1")
head(sample_hla_table_c1, row.names = FALSE)
```

```{r HLA Table for Class2}
data("sample_hla_table_c2")
head(sample_hla_table_c2, row.names = FALSE)
```

```{r RNA Expression}
data("sample_rna_exp")
head(sample_rna_exp, row.names = FALSE)
```

```{r CopyNumber Information}
data("sample_copynum")
head(sample_copynum, row.names = FALSE)
```

```{r Sample.Result.SNV.HLACLASS1}
data("sample_result_SNV_CLASS1_ALL")
head(sample_result_SNV_CLASS1_ALL, row.names = FALSE)
```

```{r Sample.Result.SNV.HLACLASS2}
data("sample_result_SNV_CLASS2_ALL")
head(sample_result_SNV_CLASS2_ALL, row.names = FALSE)
```

```{r Sample.Result.INDEL.HLACLASS1}
data("sample_result_INDEL_CLASS1_ALL")
head(sample_result_INDEL_CLASS1_ALL, row.names = FALSE)
```

```{r Sample.Result.INDEL.HLACLASS2}
data("sample_result_INDEL_CLASS2_ALL")
head(sample_result_INDEL_CLASS2_ALL)
```

```{r Sample.Result.SV.HLACLASS1}
data("sample_result_SVFusion_CLASS1_ALL")
head(sample_result_SVFusion_CLASS1_ALL, row.names = FALSE)
```

```{r Sample.Result.SV.HLACLASS2}
data("sample_result_SVFusion_CLASS2_ALL")
head(sample_result_SVFusion_CLASS2_ALL)
```

```{r Sample.Result.SeqFragment.HLACLASS1}
data("sample_result_SeqFragment_CLASS1_ALL")
head(sample_result_SeqFragment_CLASS1_ALL, row.names = FALSE)
```

```{r Sample.Result.SeqFragment.HLACLASS2}
data("sample_result_SeqFragment_CLASS2_ALL")
head(sample_result_SeqFragment_CLASS2_ALL)
```

```{r Get Sample and Test Analysis}
TestAnalysis
```
