.de Id
.ds Rv \\$3
.ds Dt \\$4
..
.Id $Header: example.1,v 1.2 94/02/15 13:28:25 rapacki Exp $
.TH NetMHCpan 1 \" -*- nroff -*-
.SH NAME
NetMHCpan 3.0 \- Prediction of peptide-MHC binding affinity for all MHC alleles of known sequence.
.SH SYNOPSIS
.B NetMHCpan
[\fB\-a\fP \fIval\fP]
[\fB\-allname\fP \fIfile\fP]
[\fB\-dirty\fP]
[\fB\-expfix\fP]
[\fB\-f\fP \fIfile\fP]
[\fB\-h\fP]
[\fB\-hlapseudo\fP \fIfile\fP]
[\fB\-hlaseq\fP \fIval\fP]
[\fB\-inptype\fP]
[\fB\-l\fP \fIval\fP]
[\fB\-listMHC\fP]
[\fB\-p\fP]
[\fB\-rdir\fP \fIdir\fP]
[\fB\-rlt\fP \fIval\fP]
[\fB\-rth\fP \fIval\fP]
[\fB\-s\fP]
[\fB\-t\fP \fIval\fP]
[\fB\-tdir\fP \fIdir\fP]
[\fB\-thrfmt\fP \fIfilefmt\fP]
[\fB\-v\fP]
[\fB\-version\fP \fIfile\fP]
[\fB\-xls\fP]
[\fB\-xlsfile\fP \fIfile\fP]
\fIINPUT\fP

.SH DESCRIPTION
.B NetMHCpan 3.0
server predicts binding of peptides to any MHC molecule of known sequence using artificial neural networks (ANNs). 
The method is trained on aboutq 180,000 quantitative binding data  covering 172 different MHC molecules from human (HLA-A, B, C, E), mouse (H-2), cattle (BoLA), primates (Patr, Mamu, Gogo) and swine (SLA). Furthermore, the user can obtain binding predictions to the any custom MHC class I molecule by uploading a full length MHC protein sequence. Furthermore, it is also possible to upload full length MHC protein sequences, and have the server predict MHC restricted peptides from any given protein of interest. Version 3.0 has been retrained on an extented data set of 8-13mer peptides using the method described in Andreatta & Nielsen, Bioinformatics, 2016. 

The \fIINPUT\fP sequences are specified as the last command line argument. Use \fB--\fP to specify input from 
\fISTDIN\fP. The output is in plain text and will be printed to \fISTDOUT\fP.
The required input format is \fBFASTA\fP or \fBPEPTIDE\fP.

.SH OPTIONS
.TP
.B "-h"
Show the help page and quit.
.TP
.BI "\-a" " string"
MHC allele name (use comman separate names without spaces for multiple alleles).
.TP
.BI "\-l" " value"
Peptide length - for FASTA submission. Specify multiple lengths as a comma-separeted list (default is 8,9,10,11).
.TP
.B "\-p"
Use \fBPEPTIDE\fP input.
.TP
.BI "\-inptype" " int"
Input type: FASTA [0] or Peptide [1] (redundant with the -p option)
.TP
.BI "\-f file"
Read input sequences from \fIfile\fP. The default is \fIINPUT\fP (without any
option flag).
.TP
.B "\-s"
Sort output in descending affinity. By default the sequences are returned in the original order.
.TP
.BI "\-t" " value"
Threshold for output. Default is -99.9 and all predictions are printed.
.TP
.BI "\-rlt" " value"
Rank threshold for low binding peptides. Default is 2% rank.
.TP
.BI "\-rth" " value"
Rank threshold for high binding peptides. Default is 0.5% rank.
.TP
.BI "\-listMHC"
Print list of alleles included in the netMHCpan library.
.TP
.B "\-xls"
Save output to XLS file.
.TP
.BI "\-xlsfile" " file"
File name for XLS output. Default is NETMHCpan_out.xls
.TP
.BI "\-hlapseudo" " file"
File with MHC pseudo sequences.
.TP
.BI "\-hlaseq" " file"
File with full length MHC protien sequence.
.TP
.BI "\-version" " file"
File with version information.
.TP
.BI "-rdir" " dir"
Home directory of netMHCpan
.TP
.BI "\-tdir" " dir"
Working directory for temporary files
.TP
.BI "\-syn" " file"
Location of the network synapse lists.
.TP
.B "\-expfix"
Exclude prefix from synlist files.
.TP
.BI "\-allname" " file"
File with MHC nomenclature conversion.
.TP
.BI "\-thrfmt" " filefmt"
Format for threshold filenames.
.TP
.B "\-dirty"
Dirty mode. Keeps all temporary files.
.TP
.B "\-v"
Use verbose mode.

.SH AUTHOR

Massimo Andreatta, massimo@cbs.dtu.dk, March 2016.
.br
.SH FILES
\fB/usr/cbs/bio/bin/netMHCpan\fP           executable
.br
\fB/usr/cbs/bio/src/netMHCpan-3.0\fP       software home
.SH SEE ALSO
fasta (1),
