#! /bin/tcsh -f

# This the main NetMHCpan 3.0 script. It only acts as the frontend to the
# software proper, a compiled binary.
# 
# VERSION:	2016 Mar 18	launch
# 

###############################################################################
#               GENERAL SETTINGS: CUSTOMIZE TO YOUR SITE
###############################################################################

# full path to the NetMHCpan 3.0 directory (mandatory)
setenv	NMHOME	/usr/cbs/packages/netMHCpan/3.0/netMHCpan-3.0

# determine where to store temporary files (must be writable to all users)
#setenv	TMPDIR $NMHOME/tmp

if ( ${?TMPDIR} == 0 ) then
	setenv  TMPDIR  /scratch
endif

# determine platform (do not change this unless you don't have 'uname'!)
setenv	UNIX	`uname -s`
setenv	AR	`uname -m`

###############################################################################
#               NOTHING SHOULD NEED CHANGING BELOW THIS LINE!
###############################################################################

# other settings
set PLATFORM = `echo $UNIX $AR | awk '{print $1"_"$2}'`
setenv NETMHCpan $NMHOME/$PLATFORM

# main ========================================================================
if ( -x $NETMHCpan/bin/netMHCpan ) then
   $NETMHCpan/bin/netMHCpan $*
else
   echo netMHCpan: no binaries found for $PLATFORM $NETMHCpan/bin/netMHCpan
endif

# end of script ===============================================================
